import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Header() {
	return (
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
}
